
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // CLI commands (migrate, db pull) use the DIRECT/unpooled Neon connection —
    // the pooled PgBouncer URL breaks Prisma Migrate
    url: env("DATABASE_URL_UNPOOLED"),
  },
});
